fixed resource naming, added negative test.

diff --git a/.github/workflows/build_and_test.yaml b/.github/workflows/build_and_test.yaml
--- a/.github/workflows/build_and_test.yaml
+++ b/.github/workflows/build_and_test.yaml
@@ -68,7 +68,8 @@ jobs:
 
         wait_for_pod_ready "sidecar"
         wait_for_pod_ready "sidecar-5xx"
-        wait_for_pod_ready "sidecar-api_key"
+        wait_for_pod_ready "sidecar-api-key"
+        wait_for_pod_ready "sidecar-api-key-fails"
         wait_for_pod_ready "dummy-server-pod"
 
     - name: Install Configmaps and Secrets
@@ -81,8 +82,9 @@ jobs:
     - name: Retrieve pod logs
       run: |
         kubectl logs sidecar > /tmp/sidecar.log
-        kubectl logs sidecar > /tmp/sidecar-api_key.log
         kubectl logs sidecar-5xx > /tmp/sidecar-5xx.log
+        kubectl logs sidecar-api-key > /tmp/sidecar-api-key.log
+        kubectl logs sidecar-api-key-fails > /tmp/sidecar-api-key-fails.log
         kubectl logs dummy-server-pod > /tmp/dummy-server.log
     - name: Upload artifacts
       uses: actions/upload-artifact@v3
@@ -111,12 +113,15 @@ jobs:
         kubectl cp sidecar-5xx:/tmp-5xx/relative/relative.txt /tmp/5xx/relative.txt
         kubectl cp sidecar-5xx:/tmp-5xx/500.txt /tmp/5xx/500.txt
 
-        echo "Downloading resource files from sidecar-api_key..."
-        kubectl cp sidecar-api_key:/tmp/api_key.txt /tmp/api-key/api_key.txt || true
+        echo "Downloading resource files from sidecar-api-key..."
+        kubectl cp sidecar-api-key:/tmp/api-key.txt /tmp/api-key/api-key.txt || true
+        
+        echo "Downloading resource files from sidecar-api-key-fails..."
+        kubectl cp sidecar-api-key-fails:/tmp/api-key.txt /tmp/api-key-fails/api-key.txt || true
 
     - name: Verify files
       run: |
-        echo "Verifying file content from sidecar and sidecar-5xx ..."
+        echo "Verifying file content from different sidecar pods ..."
         # this needs to be the last statement so that it defines the script exit code
         echo -n "Hello World!" | diff - /tmp/hello.world &&
           diff test/kubelogo.png /tmp/cm-kubelogo.png &&
@@ -132,5 +137,6 @@ jobs:
           echo -n "This relatively exists" | diff - /tmp/5xx/relative.txt &&
           echo -n "500" | diff - /tmp/5xx/500.txt &&
           ls /tmp/5xx/script_result &&
-          [ -f /tmp/api-key/api_key.txt ] && echo "api_key used for aouthentication"
+          grep "200" /tmp/api-key/api-key.txt && echo "api-key used successfully for authentication" &&
+          grep "Forbidden" /tmp/api-key-fails/api-key.txt && echo "api-key-fails expectedly with wrong credentials" 
           
